export enum BackendModule {
  LOYALTY = 'LOYALTY',
  VISITORS = 'VISITORS',
  TICKETS = 'TICKETS',
  REPORTS = 'REPORTS',
  MESSAGING = 'MESSAGING',
  PAYMENTS = 'PAYMENTS',
  SETTINGS = 'SETTINGS',
  BRANCHES = 'BRANCHES',
  BUSINESSES = 'BUSINESSES',
  ALL = 'ALL',
}
