export enum TriggerType {
    FIRST_MESSAGE = 'FIRST_MESSAGE',
    OUT_OF_OFFICE = 'OUT_OF_OFFICE',
    KEYWORD_MATCH = 'KEYWORD_MATCH',
    NEW_CONVERSATION = 'NEW_CONVERSATION',
    CUSTOM_EVENT = 'CUSTOM_EVENT'
}

export enum TargetType {
    ALL_VISITORS = 'ALL_VISITORS',
    NEW_VISITORS = 'NEW_VISITORS',
    RETURNING_VISITORS = 'RETURNING_VISITORS',
    SPECIFIC_CATEGORY = 'SPECIFIC_CATEGORY'
}

export enum ActionType {
    SEND_IN_APP_CHAT = 'SEND_IN_APP_CHAT',
    SEND_SMS = 'SEND_SMS',
    SEND_WHATSAPP = 'SEND_WHATSAPP',
    SEND_EMAIL = 'SEND_EMAIL',
    ASSIGN_TAG = 'ASSIGN_TAG'
}
