
export type BusinessCategory = { id?: string; name?: string };
export type BusinessHours = { open: string; close: string; closed: boolean };
export type BusinessBranchSummary = {
    id?: string;
    uniqueCode?: string;
    name?: string;
    isActive?: boolean;
    isMainBranch?: boolean;
    address?: string;
    city?: string;
    state?: string;
    phone?: string;
    logoUrl?: string;
    website?: string;
    whatsappNumber?: string;
    officialEmail?: string;
    about?: string;
    welcomeMessage?: string;
    businessHours?: Record<string, BusinessHours>;
    showRewards?: boolean;
    showSocial?: boolean;
    showFeedback?: boolean;
    facebookUrl?: string;
    instagramUrl?: string;
    xUrl?: string;
    linkedinUrl?: string;
    tiktokUrl?: string;
    youtubeUrl?: string;
};
export type PublicBusinessResponse = {
    id?: string;
    uniqueCode?: string;
    name?: string;
    officialEmail?: string;
    phone?: string;
    whatsappNumber?: string;
    logoUrl?: string;
    address?: string;
    state?: string;
    city?: string;
    businessHours?: Record<string, BusinessHours>;
    status?: string;
    category?: BusinessCategory;
    subcategory?: BusinessCategory;
    branches?: BusinessBranchSummary[];
    about?: string;
    welcomeMessage?: string;
    website?: string;
    instagramUrl?: string;
    facebookUrl?: string;
    xUrl?: string;
    linkedinUrl?: string;
    tiktokUrl?: string;
    youtubeUrl?: string;
    showRewards?: boolean;
};

export type PublicBranchResponse = {
    id?: string;
    uniqueCode?: string;
    name?: string;
    address?: string;
    state?: string;
    city?: string;
    phone?: string;
    logoUrl?: string;
    website?: string;
    whatsappNumber?: string;
    officialEmail?: string;
    about?: string;
    welcomeMessage?: string;
    facebookUrl?: string;
    instagramUrl?: string;
    xUrl?: string;
    linkedinUrl?: string;
    tiktokUrl?: string;
    youtubeUrl?: string;
    businessHours?: Record<string, BusinessHours>;
    isActive?: boolean;
    isMainBranch?: boolean;
    showRewards?: boolean;
    businessId?: string;
    business?: { id?: string; uniqueCode?: string; name?: string; logoUrl?: string };
};

export type PublicReward = {
    id: string;
    name: string;
    description: string;
    pointsRequired: number;
    category: string;
    audienceType: string;
    coverImage?: string | null;
    galleryImages?: string[] | null;
    totalQuantity: number;
    remainingQuantity: number;
    isActive: boolean;
    expiryDate: string;
    businessId: string;
    branchId: string;
    templateId?: string | null;
    createdAt?: string;
    updatedAt?: string;
};

export type PublicRewardsResponse = {
    data: PublicReward[];
    total: number;
    page: number;
    limit: number;
};

export type EarnVisitorPointsResponse = {
    success: boolean;
    pointsEarned: number;
    newBalance: number;
    message: string;
    customer: { id: string; uniqueCode: string };
};
